# Generated by Django 6.0 on 2025-12-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('ER', 'Experto en Emergencias'), ('UCI', 'Unidad de Cuidados Intensivos')], max_length=20)),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('especialidad', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('ER', 'Experto en Emergencias'), ('UCI', 'Unidad de Cuidados Intensivos')], max_length=20)),
                ('experiencia', models.CharField(choices=[('SENIOR', 'Senior'), ('JUNIOR', 'Junior')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=5)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('cantidad_minima_senior', models.PositiveIntegerField()),
                ('cantidad_minima_junior', models.PositiveIntegerField()),
                ('tipo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering.tipoturno')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering.empleado')),
                ('tipo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering.tipoturno')),
            ],
        ),
        migrations.CreateModel(
            name='NoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_disponibilidades', to='rostering.empleado')),
                ('tipo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rostering.tipoturno')),
            ],
            options={
                'verbose_name_plural': 'No Disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='rostering.cronograma')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering.empleado')),
                ('tipo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering.tipoturno')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
