# Generated by Django 5.2.9 on 2025-12-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencia',
            name='nivel',
            field=models.CharField(choices=[('TRABAJAR', 'Desea trabajar'), ('DESCANSAR', 'Desea descansar')], default='TRABAJAR', max_length=20),
            preserve_default=False,
        ),
    ]
