# Generated by Django 5.2.9 on 2025-12-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0002_preferencia_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoturno',
            name='duracion_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
