# Generated by Django 5.2.9 on 2025-12-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0003_alter_tipoturno_duracion_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Demanda Estándar 2025, Demanda Verano', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcepcionDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_requerida', models.IntegerField()),
                ('motivo', models.CharField(blank=True, help_text='Ej: Feriado Nacional, Refuerzo por Evento', max_length=100)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering.tipoturno')),
            ],
            options={
                'verbose_name': 'Excepción de Demanda',
                'verbose_name_plural': 'Excepciones de Demanda',
                'unique_together': {('fecha', 'turno')},
            },
        ),
        migrations.AddField(
            model_name='cronograma',
            name='plantilla_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rostering.plantillademanda'),
        ),
        migrations.CreateModel(
            name='ReglaDemandaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('cantidad_minima', models.IntegerField(default=3)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='rostering.plantillademanda')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rostering.tipoturno')),
            ],
            options={
                'verbose_name': 'Regla de Demanda Semanal',
                'verbose_name_plural': 'Reglas de Demanda Semanal',
                'unique_together': {('plantilla', 'dia', 'turno')},
            },
        ),
        migrations.DeleteModel(
            name='RequerimientoTurno',
        ),
    ]
