# Generated by Django 5.2.9 on 2025-12-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0004_plantillademanda_excepciondemanda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excepciondemanda',
            name='cantidad_requerida',
        ),
        migrations.RemoveField(
            model_name='reglademandasemanal',
            name='cantidad_minima',
        ),
        migrations.AddField(
            model_name='excepciondemanda',
            name='cantidad_junior',
            field=models.IntegerField(default=0, verbose_name='Req. Junior'),
        ),
        migrations.AddField(
            model_name='excepciondemanda',
            name='cantidad_senior',
            field=models.IntegerField(default=0, verbose_name='Req. Senior'),
        ),
        migrations.AddField(
            model_name='reglademandasemanal',
            name='cantidad_junior',
            field=models.IntegerField(default=2, verbose_name='Min. Junior'),
        ),
        migrations.AddField(
            model_name='reglademandasemanal',
            name='cantidad_senior',
            field=models.IntegerField(default=1, verbose_name='Min. Senior'),
        ),
        migrations.AlterField(
            model_name='excepciondemanda',
            name='motivo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
