# Generated by Django 5.2.9 on 2025-12-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0005_remove_excepciondemanda_cantidad_requerida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodisponibilidad',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nodisponibilidad',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rostering.tipoturno', verbose_name='Turno (Dejar vacío para todo el día)'),
        ),
    ]
