# Generated by Django 5.2.9 on 2025-12-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0006_alter_nodisponibilidad_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_dias_consecutivos', models.IntegerField(default=5, verbose_name='Máx. días consecutivos')),
                ('min_descanso_horas', models.IntegerField(default=12, verbose_name='Mín. horas descanso entre turnos')),
                ('horas_mensuales_default', models.IntegerField(default=160, verbose_name='Horas Mensuales Objetivo (Default)')),
                ('peso_preferencias', models.IntegerField(default=10, verbose_name='Peso: Respetar Preferencias')),
                ('peso_balance_carga', models.IntegerField(default=50, verbose_name='Peso: Balancear Horas')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='SecuenciaProhibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('TODOS', 'Cualquiera')], default='ENFERMERO', max_length=20)),
                ('turno_previo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibido_origen', to='rostering.tipoturno', verbose_name='Si trabaja en...')),
                ('turno_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibido_destino', to='rostering.tipoturno', verbose_name='No puede trabajar después en...')),
            ],
            options={
                'verbose_name': 'Secuencia Prohibida',
                'verbose_name_plural': 'Secuencias Prohibidas (Reglas de Oro)',
                'unique_together': {('especialidad', 'turno_previo', 'turno_siguiente')},
            },
        ),
    ]
