# Generated by Django 5.2.9 on 2025-12-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0007_configuraciongeneral_secuenciaprohibida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciongeneral',
            options={'verbose_name': 'Configuración del Algoritmo', 'verbose_name_plural': 'Configuración del Algoritmo'},
        ),
        migrations.RemoveField(
            model_name='configuraciongeneral',
            name='horas_mensuales_default',
        ),
        migrations.RemoveField(
            model_name='configuraciongeneral',
            name='min_descanso_horas',
        ),
        migrations.RemoveField(
            model_name='configuraciongeneral',
            name='peso_balance_carga',
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='peso_balance_horas',
            field=models.IntegerField(default=100, help_text='Penalización por no llegar al mínimo o pasarse del máximo de horas del empleado', verbose_name='Peso: Cumplir Carga Horaria'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='peso_equidad_turnos_dificiles',
            field=models.IntegerField(default=30, help_text='Impacto de que un empleado tenga muchas más noches/findes que sus compañeros', verbose_name='Peso: Equidad Turnos Difíciles'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tolerancia_horas',
            field=models.IntegerField(default=4, help_text='Cantidad de horas que se permite desviar del contrato sin penalización fuerte (ej. +/- 4 horas)', verbose_name='Tolerancia Horas (Absoluta)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='max_horas_mensuales',
            field=models.IntegerField(default=160, help_text='Límite superior del contrato antes de contar horas extra o prohibir', verbose_name='Máximo Horas/Mes'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='min_horas_mensuales',
            field=models.IntegerField(default=120, help_text='Límite inferior del contrato (ej. 120 para part-time)', verbose_name='Mínimo Horas/Mes'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='max_dias_consecutivos',
            field=models.IntegerField(default=5, verbose_name='Máx. días consecutivos trabajando'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='peso_preferencias',
            field=models.IntegerField(default=50, help_text='Impacto de no dar un día libre o turno solicitado', verbose_name='Peso: Respetar Preferencias'),
        ),
    ]
