# Generated by Django 5.2.9 on 2025-12-22 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0008_alter_configuraciongeneral_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlgoritmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('peso_equidad_general', models.FloatField(default=1.0, help_text='Penalización por varianza en la carga total de guardias entre médicos.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Equidad General (eq)')),
                ('peso_equidad_dificil', models.FloatField(default=1.5, help_text='Penalización por desbalance en guardias de fin de semana o nocturnas.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Equidad Difícil (dif)')),
                ('peso_preferencia_dias_libres', models.FloatField(default=2.0, help_text='Importancia de respetar los días que el médico pidió NO trabajar.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Días Libres (pdl)')),
                ('peso_preferencia_turno', models.FloatField(default=0.5, help_text='Importancia de asignar exactamente el turno solicitado (Mañana/Tarde/Noche).', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso Turno Específico (pte)')),
                ('factor_alpha_pte', models.FloatField(default=0.5, help_text='Coeficiente de penalización parcial cuando se asigna descanso en lugar del turno pedido (0 < α <= 1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Factor Alpha (α)')),
                ('tolerancia_general', models.IntegerField(default=8, help_text='Diferencia máxima de horas/turnos permitida antes de aplicar penalización severa.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tolerancia Equidad General')),
                ('tolerancia_dificil', models.IntegerField(default=4, help_text='Diferencia máxima de guardias difíciles permitida antes de penalizar.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tolerancia Equidad Difícil')),
            ],
            options={
                'verbose_name': 'Configuración del Algoritmo',
                'verbose_name_plural': 'Configuraciones del Algoritmo',
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionGeneral',
        ),
    ]
