# Generated by Django 5.2.9 on 2025-12-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0009_configuracionalgoritmo_delete_configuraciongeneral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secuenciaprohibida',
            options={'verbose_name': 'Secuencia Prohibida', 'verbose_name_plural': 'Secuencias Prohibidas'},
        ),
        migrations.RenameField(
            model_name='preferencia',
            old_name='nivel',
            new_name='deseo',
        ),
    ]
