# Generated by Django 5.2.9 on 2025-12-23 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0010_alter_secuenciaprohibida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name_plural': 'Asignaciones (Resultado)'},
        ),
        migrations.AlterModelOptions(
            name='configuracionalgoritmo',
            options={'verbose_name': 'Configuración Global del Algoritmo', 'verbose_name_plural': 'Configuraciones Globales'},
        ),
        migrations.AlterModelOptions(
            name='excepciondemanda',
            options={'verbose_name': 'Excepción de Demanda (Feriados/Picos)', 'verbose_name_plural': 'Excepciones de Demanda'},
        ),
        migrations.AlterUniqueTogether(
            name='excepciondemanda',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='mes',
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='elitismo',
            field=models.BooleanField(default=True, verbose_name='Usar Elitismo'),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='estrategia_cruce',
            field=models.CharField(choices=[('un_punto', 'Un Punto'), ('dos_puntos', 'Dos Puntos'), ('uniforme', 'Uniforme'), ('bloques_verticales', 'Bloques Verticales (Recomendado)')], default='bloques_verticales', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='estrategia_mutacion',
            field=models.CharField(choices=[('flip', 'Flip (Bit)'), ('intercambio', 'Intercambio'), ('inversion', 'Inversión'), ('hibrida_adaptativa', 'Híbrida Adaptativa (Recomendado)')], default='hibrida_adaptativa', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='estrategia_seleccion',
            field=models.CharField(choices=[('torneo_deterministico', 'Torneo Determinístico'), ('ranking', 'Ranking'), ('ruleta', 'Ruleta')], default='torneo_deterministico', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='generaciones',
            field=models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Generaciones'),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='prob_cruce',
            field=models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Probabilidad de Cruce (pc)'),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='prob_mutacion',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Probabilidad de Mutación (pm)'),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='semilla',
            field=models.IntegerField(blank=True, help_text='Dejar vacío para aleatorio. Usar número fijo para reproducibilidad.', null=True, verbose_name='Semilla (Seed)'),
        ),
        migrations.AddField(
            model_name='configuracionalgoritmo',
            name='tamano_poblacion',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Tamaño Población (pop_size)'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='configuracion_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rostering.configuracionalgoritmo'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='fecha_fin',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cronograma',
            name='fecha_inicio',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo en planificaciones'),
        ),
        migrations.AddField(
            model_name='excepciondemanda',
            name='plantilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='rostering.plantillademanda'),
        ),
        migrations.AddField(
            model_name='plantillademanda',
            name='especialidad',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('ER', 'Experto en Emergencias'), ('UCI', 'Unidad de Cuidados Intensivos')], default='MEDICO', max_length=20),
        ),
        migrations.AddField(
            model_name='preferencia',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='es_nocturno',
            field=models.BooleanField(default=False, help_text='Marcar si este turno implica penalización de descanso o secuencias prohibidas específicas.', verbose_name='Es turno nocturno'),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='especialidad',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('ER', 'Experto en Emergencias'), ('UCI', 'Unidad de Cuidados Intensivos')], default='MEDICO', max_length=20, verbose_name='Especialidad asociada'),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='activa',
            field=models.BooleanField(default=True, help_text='Solo debe haber una activa por defecto'),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='factor_alpha_pte',
            field=models.FloatField(default=0.5, help_text='Penalización parcial si se descansa en vez de trabajar el turno pedido (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='nombre',
            field=models.CharField(default='Configuración Estándar', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='peso_equidad_dificil',
            field=models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='peso_equidad_general',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='peso_preferencia_dias_libres',
            field=models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='peso_preferencia_turno',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='tolerancia_dificil',
            field=models.IntegerField(default=4, verbose_name='Tolerancia Turnos Difíciles'),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='tolerancia_general',
            field=models.IntegerField(default=8, verbose_name='Tolerancia Horas General'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('OPTIMIZANDO', 'En Proceso de Optimización'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='deseo',
            field=models.CharField(choices=[('TRABAJAR', 'Desea trabajar (Peso positivo)'), ('DESCANSAR', 'Desea descansar (Peso negativo)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rostering.tipoturno'),
        ),
        migrations.AlterField(
            model_name='secuenciaprohibida',
            name='especialidad',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('ER', 'Experto en Emergencias'), ('UCI', 'Unidad de Cuidados Intensivos')], default='ENFERMERO', max_length=20),
        ),
        migrations.AlterField(
            model_name='secuenciaprohibida',
            name='turno_previo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibido_origen', to='rostering.tipoturno'),
        ),
        migrations.AlterField(
            model_name='secuenciaprohibida',
            name='turno_siguiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibido_destino', to='rostering.tipoturno'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('cronograma', 'empleado', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='excepciondemanda',
            unique_together={('plantilla', 'fecha', 'turno')},
        ),
    ]
