# Generated by Django 5.2.9 on 2025-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0011_alter_asignacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='deseo',
            field=models.CharField(choices=[('TRABAJAR', 'Desea trabajar'), ('DESCANSAR', 'Desea descansar')], max_length=20),
        ),
    ]
