# Generated by Django 5.2.9 on 2025-12-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0012_alter_preferencia_deseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='estrategia_cruce',
            field=models.CharField(choices=[('bloques_verticales', 'Bloques Verticales'), ('bloques_horizontales', 'Bloques Horizontales'), ('dos_puntos', 'Dos Puntos')], default='bloques_verticales', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='estrategia_mutacion',
            field=models.CharField(choices=[('hibrida_adaptativa', 'Híbrida'), ('reasignar_turno', 'Reasignar Turno'), ('intercambio_dia', 'Intercambio de Día'), ('flip_simple', 'Flip Simple')], default='hibrida_adaptativa', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='estrategia_seleccion',
            field=models.CharField(choices=[('torneo_deterministico', 'Torneo Determinístico'), ('ranking_lineal', 'Ranking Lineal')], default='torneo_deterministico', max_length=50),
        ),
    ]
