# Generated by Django 5.2.9 on 2025-12-24 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0013_alter_configuracionalgoritmo_estrategia_cruce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='fitness',
            field=models.FloatField(blank=True, help_text='Puntaje de calidad (Menor/Mayor según tu función, generalmente Mayor es mejor o Menor es penalización)', null=True),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='reporte_analisis',
            field=models.JSONField(blank=True, help_text='Guarda violaciones blandas, métricas de equidad, etc.', null=True, verbose_name='Detalle de Explicabilidad (JSON)'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='tiempo_ejecucion',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo de Ejecución (s)'),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='generaciones',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Generaciones'),
        ),
    ]
