# Generated by Django 5.2.9 on 2025-12-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0014_cronograma_fitness_cronograma_reporte_analisis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoPlanificacion',
            fields=[
                ('job_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('especialidad', models.CharField(max_length=20)),
                ('payload_original', models.JSONField(help_text='Copia del JSON enviado al optimizador')),
            ],
        ),
    ]
