# Generated by Django 5.2.9 on 2025-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0015_trabajoplanificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='max_horas_mensuales',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='min_horas_mensuales',
        ),
        migrations.AddField(
            model_name='empleado',
            name='max_turnos_mensuales',
            field=models.IntegerField(default=20, help_text='Límite superior de turnos mensuales.', verbose_name='Máximo de turnos/mes'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='min_turnos_mensuales',
            field=models.IntegerField(default=15, help_text='Cantidad mínima de turnos a asignar (Ej: Para 120hs de enfermería (8hs), poner 15).', verbose_name='Mínimo de turnos/mes'),
        ),
    ]
