# Generated by Django 5.2.9 on 2025-12-25 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0016_remove_empleado_max_horas_mensuales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='max_turnos_mensuales',
            field=models.IntegerField(default=20, help_text='Límite máximo de turnos a asignar en el periodo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Máximo de turnos/mes'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='min_turnos_mensuales',
            field=models.IntegerField(default=10, help_text='Cantidad mínima de turnos a asignar en el periodo (Ej: 10 turnos de 12hs = 120hs).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mínimo de turnos/mes'),
        ),
    ]
