# Generated by Django 5.2.9 on 2026-01-01 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0017_alter_empleado_max_turnos_mensuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoplanificacion',
            name='plantilla_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rostering.plantillademanda'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='plantilla_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rostering.plantillademanda'),
        ),
        migrations.AlterField(
            model_name='excepciondemanda',
            name='cantidad_junior',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Req. Junior'),
        ),
        migrations.AlterField(
            model_name='excepciondemanda',
            name='cantidad_senior',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Req. Senior'),
        ),
        migrations.AlterField(
            model_name='excepciondemanda',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='rostering.plantillademanda'),
        ),
        migrations.AlterField(
            model_name='reglademandasemanal',
            name='cantidad_junior',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. Junior'),
        ),
        migrations.AlterField(
            model_name='reglademandasemanal',
            name='cantidad_senior',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. Senior'),
        ),
    ]
