# Generated by Django 5.2.9 on 2025-12-26 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0017_alter_empleado_max_turnos_mensuales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='plantilla_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rostering.plantillademanda'),
        ),
    ]
