# Generated by Django 5.2.9 on 2025-12-27 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0018_alter_cronograma_plantilla_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglademandasemanal',
            name='cantidad_junior',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. Junior'),
        ),
        migrations.AlterField(
            model_name='reglademandasemanal',
            name='cantidad_senior',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. Senior'),
        ),
    ]
