# Generated by Django 5.2.9 on 2025-12-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0018_alter_cronograma_plantilla_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoplanificacion',
            name='plantilla_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rostering.plantillademanda'),
        ),
    ]
