# Generated by Django 5.2.9 on 2026-01-02 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0018_trabajoplanificacion_plantilla_demanda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionalgoritmo',
            options={'verbose_name': 'Configuración del Algoritmo', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='elitismo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='factor_alpha_pte',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='prob_cruce',
            field=models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='prob_mutacion',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='semilla',
            field=models.IntegerField(blank=True, help_text='Fijar para reproducibilidad.', null=True),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='tamano_poblacion',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Población'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('OPTIMIZANDO', 'En Proceso'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='fitness',
            field=models.FloatField(blank=True, help_text='Puntaje de calidad (Mayor es mejor)', null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='reporte_analisis',
            field=models.JSONField(blank=True, null=True, verbose_name='Explicabilidad (JSON)'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='tiempo_ejecucion',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo (s)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='min_turnos_mensuales',
            field=models.IntegerField(default=10, help_text='Cantidad mínima de turnos a asignar en el periodo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mínimo de turnos/mes'),
        ),
        migrations.AlterField(
            model_name='plantillademanda',
            name='nombre',
            field=models.CharField(help_text='Ej: Demanda Estándar 2025', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajoplanificacion',
            name='payload_original',
            field=models.JSONField(),
        ),
    ]
