# Generated by Django 5.2.10 on 2026-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0019_alter_configuracionalgoritmo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('OPTIMIZANDO', 'En Proceso'), ('PUBLICADO', 'Publicado'), ('FALLIDO', 'Fallido por Cobertura')], default='BORRADOR', max_length=20),
        ),
    ]
