# Generated by Django 5.2.10 on 2026-01-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0019_alter_configuracionalgoritmo_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reglademandasemanal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reglademandasemanal',
            name='dias',
            field=models.JSONField(default=list, help_text='Lista de días (0=Lunes, 1=Martes, ..., 6=Domingo)', verbose_name='Días aplicables'),
        ),
        migrations.RemoveField(
            model_name='reglademandasemanal',
            name='dia',
        ),
    ]
