# Generated by Django 5.2.9 on 2025-12-28 00:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0019_alter_reglademandasemanal_cantidad_junior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excepciondemanda',
            name='cantidad_junior',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Req. Junior'),
        ),
        migrations.AlterField(
            model_name='excepciondemanda',
            name='cantidad_senior',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Req. Senior'),
        ),
        migrations.AlterField(
            model_name='excepciondemanda',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='rostering.plantillademanda'),
        ),
    ]
