# Generated by Django 5.2.10 on 2026-01-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0020_alter_cronograma_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='excepciondemanda',
            name='es_turno_dificil',
            field=models.BooleanField(default=False, help_text='Marcar si trabajar este día debe contar doble para la equidad (Ej: Navidad, Año Nuevo).', verbose_name='Es Turno Difícil'),
        ),
    ]
