# Generated by Django 5.2.10 on 2026-01-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0020_alter_reglademandasemanal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglademandasemanal',
            name='es_excepcion',
            field=models.BooleanField(default=False, verbose_name='Es una excepción'),
        ),
    ]
