# Generated by Django 5.2.10 on 2026-01-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0021_excepciondemanda_es_turno_dificil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('ER', 'Experto en Emergencias'), ('UCI', 'Unidad de Cuidados Intensivos')], max_length=20, unique=True, verbose_name='Especialidad')),
                ('esquema', models.CharField(choices=[('2x12', '2 Turnos de 12 Horas (Total 24hs)'), ('3x8', '3 Turnos de 8 Horas (Total 24hs)')], default='2x12', max_length=10)),
                ('hora_inicio_base', models.TimeField(help_text='Ej: 08:00. El resto se calcula automáticamente.', verbose_name='Hora de Inicio (Primer Turno)')),
                ('nombres_turnos', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
