# Generated by Django 5.2.10 on 2026-01-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0021_reglademandasemanal_es_excepcion'),
        ('rostering', '0022_configuracionturnos'),
    ]

    operations = [
    ]
