# Generated by Django 5.2.10 on 2026-01-21 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0023_merge_20260113_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='generaciones',
            field=models.IntegerField(default=15, help_text='Cantidad de generaciones (entre 1 y 10000).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Generaciones'),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='semilla',
            field=models.IntegerField(blank=True, help_text='Fijar para reproducibilidad (entero no negativo).', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='tamano_poblacion',
            field=models.IntegerField(default=100, help_text='Tamaño de la población (entre 10 y 10000).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)], verbose_name='Población'),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='tolerancia_dificil',
            field=models.IntegerField(default=4, help_text='Tolerancia para turnos difíciles (0-168).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)], verbose_name='Tolerancia Turnos Difíciles'),
        ),
        migrations.AlterField(
            model_name='configuracionalgoritmo',
            name='tolerancia_general',
            field=models.IntegerField(default=8, help_text='Horas de tolerancia general (0-168).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)], verbose_name='Tolerancia Horas General'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='max_turnos_mensuales',
            field=models.IntegerField(default=20, help_text='Límite máximo de turnos a asignar en el periodo.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Máximo de turnos/mes'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='min_turnos_mensuales',
            field=models.IntegerField(default=10, help_text='Cantidad mínima de turnos a asignar en el periodo.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Mínimo de turnos/mes'),
        ),
        migrations.AlterField(
            model_name='nodisponibilidad',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantillademanda',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
